In [1]:
import Quandl

In [ ]:
def get_stock(symbol, trim_start="2005-01-01", trim_end="2015-12-31"):
    return Quandl.get(symbol,authtoken='c2365v55yoZrWKxbVxwK', trim_start = trim_start, trim_end = trim_end)

In [14]:
s_MSFT_p = Quandl.get('GOOG/NASDAQ_MSFT',authtoken='c2365v55yoZrWKxbVxwK',trim_start = "2005-01-01")

In [7]:
s_JPM_p = Quandl.get('GOOG/NYSE_JPM',authtoken='c2365v55yoZrWKxbVxwK',trim_start = "2005-01-01")

In [18]:
s_GOOGL_p = Quandl.get('GOOG/NASDAQ_GOOGL',authtoken='c2365v55yoZrWKxbVxwK',trim_start = "2005-01-01")

In [10]:
import json

In [16]:
s_MSFT_p.to_csv('msft.csv')

In [17]:
s_JPM_p.to_csv('jpm.csv')

In [19]:
s_GOOGL_p.to_csv('googl.csv')

In [20]:
s_SP500_p = Quandl.get('GOOG/NYSE_SPY',authtoken='c2365v55yoZrWKxbVxwK',trim_start = "2005-01-01")

In [21]:
s_SP500_p.to_csv('sp500.csv')

In [22]:
s_SP500_p

              Open    High     Low   Close     Volume
Date
2005-01-03  121.56  121.76  119.90  120.30   53923500
2005-01-04  120.46  120.53  118.44  118.73   65110000
2005-01-05  118.74  119.25  118.00  118.01   63001300
2005-01-06  118.48  119.15  118.26  118.61   46049600
2005-01-07  118.97  119.23  118.13  118.44   53134500
2005-01-10  118.34  119.46  118.34  119.00   55027400
2005-01-11  118.65  118.74  117.99  118.18   59703100
2005-01-12  118.39  118.84  117.34  118.57   69597900
2005-01-13  118.64  118.73  117.50  117.62   53385000
2005-01-14  117.97  118.53  117.76  118.24   39497700
2005-01-18  118.05  119.63  117.95  119.47   52832200
2005-01-19  119.42  119.52  118.21  118.22   50922300
2005-01-20  117.89  118.20  117.29  117.50   69582800
2005-01-21  117.79  118.00  116.65  116.78   61026900
2005-01-24  117.09  117.34  116.37  116.55   56921100
2005-01-25  116.91  117.47  116.72  116.88   65531300
2005-01-26  117.31  117.60  117.04  117.23   55169200
2005-01-27  117.19  117.75  116.98  117.43   52889700
2005-01-28  117.49  117.55  116.61  117.43   58695800
2005-01-31  117.97  118.25  117.71  118.16   49495600
2005-02-01  118.25  119.08  118.10  118.91   49426000
2005-02-02  119.06  119.59  118.90  119.27   51556800
2005-02-03  119.07  119.16  118.07  118.96   46752600
2005-02-04  119.00  120.43  118.98  120.23   46233000
2005-02-07  120.22  120.52  119.96  120.07   45504600
2005-02-08  120.17  120.65  120.07  120.21   38158700
2005-02-09  120.42  120.49  119.25  119.31   54167900
2005-02-10  119.66  120.02  119.26  119.74   44774200
2005-02-11  119.71  121.04  119.46  120.77   52029900
2005-02-14  120.69  120.86  120.48  120.68   29630300
...            ...     ...     ...     ...        ...
2016-03-17  203.24  205.23  202.77  204.63  130871283
2016-03-18  204.17  204.78  203.80  204.38  134715170
2016-03-21  204.07  204.94  203.80  204.67   70591212
2016-03-22  203.76  205.23  203.57  204.56   96209380
2016-03-23  204.11  204.33  203.01  203.21   79840502
2016-03-24  202.00  203.16  201.74  203.12   83607327
2016-03-28  203.61  203.86  202.70  203.24   61514340
2016-03-29  202.76  205.25  202.40  205.12   90977994
2016-03-30  206.30  206.87  205.59  206.02   83166291
2016-03-31  205.91  206.41  205.33  205.52   93143793
2016-04-01  204.35  207.14  203.98  206.92  112704924
2016-04-04  206.83  207.07  205.89  206.25   62340197
2016-04-05  204.67  206.26  203.89  204.19   90930441
2016-04-06  204.29  206.49  203.98  206.42   91167807
2016-04-07  205.14  205.56  203.09  203.95  111208660
2016-04-08  205.34  205.85  203.87  204.50   94553515
2016-04-11  205.25  206.07  203.91  204.02   81496090
2016-04-12  204.22  206.25  203.70  205.92  113056789
2016-04-13  207.00  208.10  206.84  208.00   93840162
2016-04-14  208.07  208.60  207.60  208.01   64763839
2016-04-15  208.01  208.17  207.40  207.78   75123038
2016-04-18  207.14  209.28  207.00  209.24   81477881
2016-04-19  209.74  210.20  208.94  209.90   86869547
2016-04-20  209.95  210.92  209.39  210.10   77333907
2016-04-21  210.12  210.25  208.65  208.97   80790054
2016-04-22  208.55  209.29  207.91  208.97   97485534
2016-04-25  208.26  208.66  207.54  208.61   65772156
2016-04-26  209.04  209.52  208.36  208.92   73631053
2016-04-27  208.47  209.81  208.05  209.35   74785306
2016-04-28  208.46  209.76  206.96  207.45   95931092

[2863 rows x 5 columns]